version: '3'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    ports: 
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: db

  node:
    image: node:latest
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    command: 'bash -c "npm i && npm run dev"'
    container_name: node